//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ordisoftware.Hebrew.Words.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.0.3.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Center")]
        public global::Ordisoftware.Core.ControlLocation MainFormPosition {
            get {
                return ((global::Ordisoftware.Core.ControlLocation)(this["MainFormPosition"]));
            }
            set {
                this["MainFormPosition"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int MainFormLeft {
            get {
                return ((int)(this["MainFormLeft"]));
            }
            set {
                this["MainFormLeft"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int MainFormTop {
            get {
                return ((int)(this["MainFormTop"]));
            }
            set {
                this["MainFormTop"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int MainFormWidth {
            get {
                return ((int)(this["MainFormWidth"]));
            }
            set {
                this["MainFormWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int MainFormHeight {
            get {
                return ((int)(this["MainFormHeight"]));
            }
            set {
                this["MainFormHeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Normal")]
        public global::System.Windows.Forms.FormWindowState MainFormState {
            get {
                return ((global::System.Windows.Forms.FormWindowState)(this["MainFormState"]));
            }
            set {
                this["MainFormState"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ConfirmClosing {
            get {
                return ((bool)(this["ConfirmClosing"]));
            }
            set {
                this["ConfirmClosing"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowTips {
            get {
                return ((bool)(this["ShowTips"]));
            }
            set {
                this["ShowTips"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Verses")]
        public global::Ordisoftware.Hebrew.Words.ViewMode CurrentView {
            get {
                return ((global::Ordisoftware.Hebrew.Words.ViewMode)(this["CurrentView"]));
            }
            set {
                this["CurrentView"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool UpgradeRequired {
            get {
                return ((bool)(this["UpgradeRequired"]));
            }
            set {
                this["UpgradeRequired"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("c:\\Program Files\\Ordisoftware\\Hebrew Letters\\Bin\\Ordisoftware.HebrewLetters.exe")]
        public string HebrewLettersExe {
            get {
                return ((string)(this["HebrewLettersExe"]));
            }
            set {
                this["HebrewLettersExe"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://www.pealim.com/search/?q=%WORD%")]
        public string SearchOnlineURL {
            get {
                return ((string)(this["SearchOnlineURL"]));
            }
            set {
                this["SearchOnlineURL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string BackupPath {
            get {
                return ((string)(this["BackupPath"]));
            }
            set {
                this["BackupPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public int BackupCount {
            get {
                return ((int)(this["BackupCount"]));
            }
            set {
                this["BackupCount"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public int AutoSaveDelay {
            get {
                return ((int)(this["AutoSaveDelay"]));
            }
            set {
                this["AutoSaveDelay"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SearchTranslated")]
        public global::Ordisoftware.Hebrew.Words.HebrewWordClickOpen HebrewWordClickOpen {
            get {
                return ((global::Ordisoftware.Hebrew.Words.HebrewWordClickOpen)(this["HebrewWordClickOpen"]));
            }
            set {
                this["HebrewWordClickOpen"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://studybible.info/IHOT/%BOOKSB% %CHAPTERNUM%:%VERSENUM%")]
        public string OpenVerseOnlineURL {
            get {
                return ((string)(this["OpenVerseOnlineURL"]));
            }
            set {
                this["OpenVerseOnlineURL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int VerseCommentaryLinesCount {
            get {
                return ((int)(this["VerseCommentaryLinesCount"]));
            }
            set {
                this["VerseCommentaryLinesCount"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20")]
        public int BookmarksCount {
            get {
                return ((int)(this["BookmarksCount"]));
            }
            set {
                this["BookmarksCount"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int BookmarkMasterBook {
            get {
                return ((int)(this["BookmarkMasterBook"]));
            }
            set {
                this["BookmarkMasterBook"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int BookmarkMasterChapter {
            get {
                return ((int)(this["BookmarkMasterChapter"]));
            }
            set {
                this["BookmarkMasterChapter"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int BookmarkMasterVerse {
            get {
                return ((int)(this["BookmarkMasterVerse"]));
            }
            set {
                this["BookmarkMasterVerse"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("205")]
        public int WordControlWidth {
            get {
                return ((int)(this["WordControlWidth"]));
            }
            set {
                this["WordControlWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20")]
        public int FoundReferencesViewable {
            get {
                return ((int)(this["FoundReferencesViewable"]));
            }
            set {
                this["FoundReferencesViewable"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("292, 466")]
        public global::System.Drawing.Size SearchTranslatedFormSize {
            get {
                return ((global::System.Drawing.Size)(this["SearchTranslatedFormSize"]));
            }
            set {
                this["SearchTranslatedFormSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1, -1")]
        public global::System.Drawing.Point SearchTranslatedFormLocation {
            get {
                return ((global::System.Drawing.Point)(this["SearchTranslatedFormLocation"]));
            }
            set {
                this["SearchTranslatedFormLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20")]
        public int HistoryCount {
            get {
                return ((int)(this["HistoryCount"]));
            }
            set {
                this["HistoryCount"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20")]
        public int FoundReferencesToOpenDialog {
            get {
                return ((int)(this["FoundReferencesToOpenDialog"]));
            }
            set {
                this["FoundReferencesToOpenDialog"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1, -1")]
        public global::System.Drawing.Point GrammarGuideFormLocation {
            get {
                return ((global::System.Drawing.Point)(this["GrammarGuideFormLocation"]));
            }
            set {
                this["GrammarGuideFormLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("492, 566")]
        public global::System.Drawing.Size GrammarGuideFormSize {
            get {
                return ((global::System.Drawing.Size)(this["GrammarGuideFormSize"]));
            }
            set {
                this["GrammarGuideFormSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool SearchTranslatedFormFilterDistinct {
            get {
                return ((bool)(this["SearchTranslatedFormFilterDistinct"]));
            }
            set {
                this["SearchTranslatedFormFilterDistinct"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int CurrentSearchTypeTab {
            get {
                return ((int)(this["CurrentSearchTypeTab"]));
            }
            set {
                this["CurrentSearchTypeTab"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool CheckUpdateAtStartup {
            get {
                return ((bool)(this["CheckUpdateAtStartup"]));
            }
            set {
                this["CheckUpdateAtStartup"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool CloseSearchTranslatedFormReturnToReference {
            get {
                return ((bool)(this["CloseSearchTranslatedFormReturnToReference"]));
            }
            set {
                this["CloseSearchTranslatedFormReturnToReference"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool OpenLastViewAtStartup {
            get {
                return ((bool)(this["OpenLastViewAtStartup"]));
            }
            set {
                this["OpenLastViewAtStartup"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool SearchInTorah {
            get {
                return ((bool)(this["SearchInTorah"]));
            }
            set {
                this["SearchInTorah"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SearchInNeviim {
            get {
                return ((bool)(this["SearchInNeviim"]));
            }
            set {
                this["SearchInNeviim"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SearchInKetouvim {
            get {
                return ((bool)(this["SearchInKetouvim"]));
            }
            set {
                this["SearchInKetouvim"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("792, 666")]
        public global::System.Drawing.Size ImportVerseFormSize {
            get {
                return ((global::System.Drawing.Size)(this["ImportVerseFormSize"]));
            }
            set {
                this["ImportVerseFormSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool OpenGeneratedMSWordFiles {
            get {
                return ((bool)(this["OpenGeneratedMSWordFiles"]));
            }
            set {
                this["OpenGeneratedMSWordFiles"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int SearchInBookSelectedNumber {
            get {
                return ((int)(this["SearchInBookSelectedNumber"]));
            }
            set {
                this["SearchInBookSelectedNumber"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("200")]
        public int ImportVerseFormSplitterDistance {
            get {
                return ((int)(this["ImportVerseFormSplitterDistance"]));
            }
            set {
                this["ImportVerseFormSplitterDistance"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("None")]
        public global::Ordisoftware.Core.Language LanguageSelected {
            get {
                return ((global::Ordisoftware.Core.Language)(this["LanguageSelected"]));
            }
            set {
                this["LanguageSelected"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("130")]
        public int FoundReferencesColumnRefWidth {
            get {
                return ((int)(this["FoundReferencesColumnRefWidth"]));
            }
            set {
                this["FoundReferencesColumnRefWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ReachReference")]
        public global::Ordisoftware.Hebrew.Words.TranslatedItemDoubleClickOpen TranslatedItemDoubleClickOpen {
            get {
                return ((global::Ordisoftware.Hebrew.Words.TranslatedItemDoubleClickOpen)(this["TranslatedItemDoubleClickOpen"]));
            }
            set {
                this["TranslatedItemDoubleClickOpen"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("492, 266")]
        public global::System.Drawing.Size EditMemoFormClientSize {
            get {
                return ((global::System.Drawing.Size)(this["EditMemoFormClientSize"]));
            }
            set {
                this["EditMemoFormClientSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("692, 666")]
        public global::System.Drawing.Size EditBooksFormClientSize {
            get {
                return ((global::System.Drawing.Size)(this["EditBooksFormClientSize"]));
            }
            set {
                this["EditBooksFormClientSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool GoToMasterBookmarkAtStartup {
            get {
                return ((bool)(this["GoToMasterBookmarkAtStartup"]));
            }
            set {
                this["GoToMasterBookmarkAtStartup"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("150")]
        public int ImportVerseFormGridColumnWidthHebrew {
            get {
                return ((int)(this["ImportVerseFormGridColumnWidthHebrew"]));
            }
            set {
                this["ImportVerseFormGridColumnWidthHebrew"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("250")]
        public int ImportVerseFormGridColumnWidthTranslationCurrent {
            get {
                return ((int)(this["ImportVerseFormGridColumnWidthTranslationCurrent"]));
            }
            set {
                this["ImportVerseFormGridColumnWidthTranslationCurrent"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool AutoSortBookmarks {
            get {
                return ((bool)(this["AutoSortBookmarks"]));
            }
            set {
                this["AutoSortBookmarks"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool VacuumAtStartup {
            get {
                return ((bool)(this["VacuumAtStartup"]));
            }
            set {
                this["VacuumAtStartup"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool DebuggerEnabled {
            get {
                return ((bool)(this["DebuggerEnabled"]));
            }
            set {
                this["DebuggerEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.DateTime VacuumLastDone {
            get {
                return ((global::System.DateTime)(this["VacuumLastDone"]));
            }
            set {
                this["VacuumLastDone"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.DateTime CheckUpdateLastDone {
            get {
                return ((global::System.DateTime)(this["CheckUpdateLastDone"]));
            }
            set {
                this["CheckUpdateLastDone"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1, -1")]
        public global::System.Drawing.Point TraceFormLocation {
            get {
                return ((global::System.Drawing.Point)(this["TraceFormLocation"]));
            }
            set {
                this["TraceFormLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("884, 661")]
        public global::System.Drawing.Size TraceFormSize {
            get {
                return ((global::System.Drawing.Size)(this["TraceFormSize"]));
            }
            set {
                this["TraceFormSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("8")]
        public int TraceFormTextBoxFontSize {
            get {
                return ((int)(this["TraceFormTextBoxFontSize"]));
            }
            set {
                this["TraceFormTextBoxFontSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool TraceEnabled {
            get {
                return ((bool)(this["TraceEnabled"]));
            }
            set {
                this["TraceEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool SoundsEnabled {
            get {
                return ((bool)(this["SoundsEnabled"]));
            }
            set {
                this["SoundsEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool AdvancedDialogBoxes {
            get {
                return ((bool)(this["AdvancedDialogBoxes"]));
            }
            set {
                this["AdvancedDialogBoxes"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool FirstLaunch {
            get {
                return ((bool)(this["FirstLaunch"]));
            }
            set {
                this["FirstLaunch"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool UsageStatisticsEnabled {
            get {
                return ((bool)(this["UsageStatisticsEnabled"]));
            }
            set {
                this["UsageStatisticsEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public long BenchmarkLoadData {
            get {
                return ((long)(this["BenchmarkLoadData"]));
            }
            set {
                this["BenchmarkLoadData"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public long BenchmarkStartingApp {
            get {
                return ((long)(this["BenchmarkStartingApp"]));
            }
            set {
                this["BenchmarkStartingApp"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public int ApplicationVolume {
            get {
                return ((int)(this["ApplicationVolume"]));
            }
            set {
                this["ApplicationVolume"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("7")]
        public int CheckUpdateAtStartupDaysInterval {
            get {
                return ((int)(this["CheckUpdateAtStartupDaysInterval"]));
            }
            set {
                this["CheckUpdateAtStartupDaysInterval"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("7")]
        public int VacuumAtStartupDaysInterval {
            get {
                return ((int)(this["VacuumAtStartupDaysInterval"]));
            }
            set {
                this["VacuumAtStartupDaysInterval"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool WebLinksMenuEnabled {
            get {
                return ((bool)(this["WebLinksMenuEnabled"]));
            }
            set {
                this["WebLinksMenuEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1, -1")]
        public global::System.Drawing.Point ParashotFormLocation {
            get {
                return ((global::System.Drawing.Point)(this["ParashotFormLocation"]));
            }
            set {
                this["ParashotFormLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("984, 676")]
        public global::System.Drawing.Size ParashotFormClientSize {
            get {
                return ((global::System.Drawing.Size)(this["ParashotFormClientSize"]));
            }
            set {
                this["ParashotFormClientSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Normal")]
        public global::System.Windows.Forms.FormWindowState ParashotFormWindowState {
            get {
                return ((global::System.Windows.Forms.FormWindowState)(this["ParashotFormWindowState"]));
            }
            set {
                this["ParashotFormWindowState"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("8")]
        public decimal ParashotFormFontSize {
            get {
                return ((decimal)(this["ParashotFormFontSize"]));
            }
            set {
                this["ParashotFormFontSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1")]
        public int ParashotFormColumnTranslationWidth {
            get {
                return ((int)(this["ParashotFormColumnTranslationWidth"]));
            }
            set {
                this["ParashotFormColumnTranslationWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowLastNewInVersionAfterUpdate {
            get {
                return ((bool)(this["ShowLastNewInVersionAfterUpdate"]));
            }
            set {
                this["ShowLastNewInVersionAfterUpdate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool FirstLaunchV3_0 {
            get {
                return ((bool)(this["FirstLaunchV3_0"]));
            }
            set {
                this["FirstLaunchV3_0"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public long BenchmarkTranslate {
            get {
                return ((long)(this["BenchmarkTranslate"]));
            }
            set {
                this["BenchmarkTranslate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool LoadingFormHidden {
            get {
                return ((bool)(this["LoadingFormHidden"]));
            }
            set {
                this["LoadingFormHidden"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Dsn=Hebrew-Words")]
        public string ConnectionString {
            get {
                return ((string)(this["ConnectionString"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool TraceFormShowOnlyErrors {
            get {
                return ((bool)(this["TraceFormShowOnlyErrors"]));
            }
            set {
                this["TraceFormShowOnlyErrors"] = value;
            }
        }
    }
}
